### ISSUE TITLE
Uncaught Error: Bootstrap dropdown require Popper.js

### ISSUE THREAD

**Issue by lordchewie** [Kthulu120/liquid_dl#4]
Trying to get this docker image all finalized but still running into this. Tried to run the app locally and got the same thing.

Since you've got it running locally, could it be a dependency that was not added to package.json?

**Comment by lordchewie** [comment]
Also other issue: Uncaught ReferenceError: YoutubeDLForm is not defined

**Comment by Kthulu120** [comment]
Issue was due to Bootstrap 4 requiring popper.js in a very specific manner therefore I eliminated it as a dependency and replaced it with Bootstrap 3 and will attempt to optimize the Webpack bundle in upcoming releases and getting rid of unneeded dependencies.

Should be resolved with the newest commit 80c477423c39355b0ade81f79cc9b2eb73f4877f.
